MODEL_DIR: 
REMOTE_MODEL_DIR: /mnt/sdcard/tflite_bench
KERNEL_PATH: /mnt/sdcard/tflite_bench/kernel.cl
BENCHMARK_MODEL_PATH: /data/local/tmp/benchmark_model_fixed_group_size
DEVICE_SERIAL: 0000028e2c780e4e
