BLOCK:   ###configuration for blocks, see generator.config_block.py
      BLOCK_TYPE: bn
      CIN_MAX: 640
      CIN_MIN: 16
      COUT_MAX: 640
      COUT_MIN: 16
      CSTEP_MIN: 4 ## minimal sampling step for channel number
      SAMPLE_NUM: 4000
      ##variables for configurations
      KERNEL_SIZE: [1,3,5,7,9]
      STRIDE: [1,2]
      HW: [28]
    
 

